"""World Happiness Analytics — full analysis.

Reads data/happiness.csv (generated by data/generate_happiness_data.py,
seed=42), runs the analysis, saves charts to images/, and writes
results_summary.txt with every headline number (used for the README).

Sections: headline KPIs -> correlations -> OLS regression -> GDP scatter ->
regional trends -> climbers & fallers -> SQL cross-check values.
"""

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression

sns.set_theme(style="whitegrid")

df = pd.read_csv("../data/happiness.csv")
LATEST = df["year"].max()          # 2024
BASE = df["year"].min()           # 2019
FACTORS = ["log_gdp_per_capita", "social_support", "healthy_life_expectancy",
           "freedom", "generosity", "corruption_perception"]
FACTOR_LABELS = {"log_gdp_per_capita": "log GDP per capita",
                 "social_support": "social support",
                 "healthy_life_expectancy": "healthy life expectancy",
                 "freedom": "freedom",
                 "generosity": "generosity",
                 "corruption_perception": "corruption perception"}
d24 = df[df["year"] == LATEST].copy()

out = []
def log(line=""):
    print(line)
    out.append(line)

# ================================================== 1. Headline KPIs ===
log("=== Headline KPIs (2024) ===")
global_avg = d24["ladder_score"].mean()
log(f"Global average ladder score ({LATEST}): {global_avg:.3f}")
log(f"Countries: {d24['country'].nunique()} | Regions: {d24['region'].nunique()}")

top10 = d24.nlargest(10, "ladder_score")[["country", "region", "ladder_score"]]
log("\nTop 10 countries:")
log(top10.to_string(index=False))
bottom5 = d24.nsmallest(5, "ladder_score")[["country", "region", "ladder_score"]]
log("\nBottom 5 countries:")
log(bottom5.to_string(index=False))

region_avg = d24.groupby("region")["ladder_score"].mean().sort_values(ascending=False)
log("\nAverage ladder by region (2024):")
log(region_avg.round(3).to_string())
log(f"\nBest region: {region_avg.index[0]} ({region_avg.iloc[0]:.3f})")
log(f"Worst region: {region_avg.index[-1]} ({region_avg.iloc[-1]:.3f})")

fig, ax = plt.subplots(figsize=(10, 6))
t10 = top10.iloc[::-1]
ax.barh(t10["country"], t10["ladder_score"], color="#2a7f62")
ax.set_xlabel("Ladder score (0-10)")
ax.set_title(f"Top 10 happiest countries ({LATEST})")
for i, v in enumerate(t10["ladder_score"]):
    ax.text(v + 0.03, i, f"{v:.2f}", va="center", fontsize=9)
ax.set_xlim(0, t10["ladder_score"].max() * 1.12)
plt.tight_layout(); plt.savefig("../images/top10_bar.png", dpi=120); plt.close()

# ================================================= 2. Correlations ===
log("\n=== Correlations with ladder score (all years) ===")
corr = df[FACTORS + ["ladder_score"]].corr()["ladder_score"].drop("ladder_score")
log(corr.round(3).to_string())

fig, ax = plt.subplots(figsize=(9, 7))
cm = df[FACTORS + ["ladder_score"]].corr()
sns.heatmap(cm, annot=True, fmt=".2f", cmap="RdYlGn", vmin=-0.6, vmax=1.0,
            square=True, ax=ax, cbar_kws={"label": "Pearson r"})
ax.set_title("Correlation matrix: happiness factors vs ladder score")
ax.set_xticklabels([FACTOR_LABELS.get(c, c) for c in cm.columns], rotation=30, ha="right")
ax.set_yticklabels([FACTOR_LABELS.get(c, c) for c in cm.index], rotation=0)
plt.tight_layout(); plt.savefig("../images/correlation_heatmap.png", dpi=120); plt.close()

# =========================================== 3. OLS regression ===
log("\n=== OLS regression: ladder ~ 6 factors (standardized) ===")
X = d24[FACTORS].values
y = d24["ladder_score"].values
Xz = (X - X.mean(0)) / X.std(0, ddof=0)
yz = (y - y.mean()) / y.std(ddof=0)
model = LinearRegression().fit(Xz, yz)
r2 = model.score(Xz, yz)
std_coefs = pd.Series(model.coef_, index=FACTORS).sort_values(ascending=False,
    key=lambda s: s.abs())
log(f"R² = {r2:.3f}  (n = {len(d24)} countries, {LATEST})")
log("Standardized coefficients (|coef| = effect of +1 SD in factor):")
for f, c in std_coefs.items():
    log(f"  {FACTOR_LABELS[f]:24s} {c:+.3f}")
top_factor = std_coefs.index[0]
log(f"Strongest driver: {FACTOR_LABELS[top_factor]} ({std_coefs.iloc[0]:+.3f})")

# ====================================== 4. GDP vs ladder scatter ===
log("\n=== GDP vs ladder ===")
fig, ax = plt.subplots(figsize=(10, 6))
regions = sorted(d24["region"].unique())
palette = dict(zip(regions, sns.color_palette("tab10", len(regions))))
for r in regions:
    sub = d24[d24["region"] == r]
    ax.scatter(sub["log_gdp_per_capita"], sub["ladder_score"], s=28,
               label=r, color=palette[r], alpha=0.8, edgecolor="white",
               linewidth=0.4)
xs = np.linspace(d24["log_gdp_per_capita"].min(), d24["log_gdp_per_capita"].max(), 100)
b, a = np.polyfit(d24["log_gdp_per_capita"], d24["ladder_score"], 1)
ax.plot(xs, a + b * xs, color="black", lw=1.6, ls="--",
        label=f"trend (slope {b:.2f})")
ax.set_xlabel("log GDP per capita")
ax.set_ylabel("Ladder score (0-10)")
ax.set_title(f"Wealth vs happiness ({LATEST}) — one dot per country")
ax.legend(fontsize=8, loc="upper left", ncol=2)
plt.tight_layout(); plt.savefig("../images/gdp_vs_ladder_scatter.png", dpi=120); plt.close()
log(f"GDP-ladder Pearson r = {d24['log_gdp_per_capita'].corr(d24['ladder_score']):.3f}")

# ========================================= 5. Regional trends ===
log("\n=== Regional trends 2019-2024 ===")
trend = df.groupby(["region", "year"])["ladder_score"].mean().unstack("year")
change = (trend[LATEST] - trend[BASE]).sort_values(ascending=False)
log("Change in regional avg ladder, 2019 -> 2024:")
log(change.round(3).to_string())
log(f"\nBiggest riser: {change.index[0]} ({change.iloc[0]:+.3f})")
log(f"Biggest faller: {change.index[-1]} ({change.iloc[-1]:+.3f})")

fig, ax = plt.subplots(figsize=(10, 6))
for r in trend.index:
    ax.plot(trend.columns, trend.loc[r], marker="o", ms=4, label=r,
            color=palette[r], lw=2)
ax.set_xlabel("Year"); ax.set_ylabel("Average ladder score")
ax.set_title("Happiness trends by region, 2019-2024")
ax.legend(fontsize=8, loc="center left", bbox_to_anchor=(1, 0.5))
plt.tight_layout(); plt.savefig("../images/regional_trends.png", dpi=120); plt.close()

# ==================================== 6. Climbers & fallers ===
log("\n=== Biggest climbers & fallers (2019 -> 2024) ===")
piv = df.pivot_table(index=["country", "region"], columns="year",
                     values="ladder_score")
piv["change"] = piv[LATEST] - piv[BASE]
piv = piv.reset_index()
climbers = piv.nlargest(5, "change")
fallers = piv.nsmallest(5, "change")
log("Top 5 climbers:")
log(climbers[["country", "region", "change"]].to_string(index=False,
    formatters={"change": "{:+.3f}".format}))
log("\nTop 5 fallers:")
log(fallers[["country", "region", "change"]].to_string(index=False,
    formatters={"change": "{:+.3f}".format}))
biggest_climber = (climbers.iloc[0]["country"], climbers.iloc[0]["change"])
biggest_faller = (fallers.iloc[0]["country"], fallers.iloc[0]["change"])

fig, axes = plt.subplots(1, 2, figsize=(12, 5), sharex=False)
c5 = climbers.iloc[::-1]
axes[0].barh(c5["country"], c5["change"], color="#2a7f62")
axes[0].set_title("Biggest climbers 2019-2024")
axes[0].set_xlabel("Ladder change")
f5 = fallers.iloc[::-1]
axes[1].barh(f5["country"], f5["change"], color="#b03a2e")
axes[1].set_title("Biggest fallers 2019-2024")
axes[1].set_xlabel("Ladder change")
for axi in axes:
    for i, v in enumerate(axi.patches):
        w = v.get_width()
        axi.text(w + (0.02 if w > 0 else -0.02), v.get_y() + v.get_height()/2,
                 f"{w:+.2f}", va="center", ha="left" if w > 0 else "right",
                 fontsize=9)
plt.tight_layout(); plt.savefig("../images/climbers_fallers.png", dpi=120); plt.close()

# ============================ 7. SQL cross-check values (GDP quartiles) ===
# Quartiles computed the NTILE(4) way (row-count buckets), exactly matching
# the MySQL NTILE(4) OVER (ORDER BY log_gdp_per_capita) in sql/queries.sql.
log("\n=== GDP quartile avgs 2024 (for SQL Q5 cross-check) ===")
d24q = d24.sort_values("log_gdp_per_capita").reset_index(drop=True)
d24q["gdp_quartile"] = (np.arange(len(d24q)) // 40) + 1
d24q["gdp_quartile"] = d24q["gdp_quartile"].map(
    {1: "Q1 (poorest)", 2: "Q2", 3: "Q3", 4: "Q4 (richest)"})
qavg = d24q.groupby("gdp_quartile", observed=True)["ladder_score"].mean()
log(qavg.round(3).to_string())

log("\n=== YoY global trend (for SQL Q6 cross-check) ===")
yoy = df.groupby("year")["ladder_score"].mean()
log(yoy.round(3).to_string())

with open("../results_summary.txt", "w") as f:
    f.write("\n".join(out) + "\n")
log("\nwrote ../results_summary.txt and 5 charts to ../images/")
